[workspace]
members = [
    "aggregator",
    "aggregator_api",
    "aggregator_core",
    "build_script_utils",
    "client",
    "collector",
    "core",
    "integration_tests",
    "interop_binaries",
    "messages",
    "tools",
]
resolver = "2"

[workspace.package]
edition = "2021"
homepage = "https://divviup.org"
license = "MPL-2.0"
repository = "https://github.com/divviup/janus"
rust-version = "1.65.0"
version = "0.5.0"

[workspace.dependencies]
anyhow = "1"
# Disable default features to disable compatibility with the old `time` crate, and we also don't
# (yet) need other default features.
# https://docs.rs/chrono/latest/chrono/#duration
chrono = { version = "0.4", default-features = false }
itertools = "0.10"
janus_aggregator = { version = "0.5", path = "aggregator" }
janus_aggregator_api = { version = "0.5", path = "aggregator_api" }
janus_aggregator_core = { version = "0.5", path = "aggregator_core" }
janus_build_script_utils = { version = "0.5", path = "build_script_utils" }
janus_client = { version = "0.5", path = "client" }
janus_collector = { version = "0.5", path = "collector" }
janus_core = { version = "0.5", path = "core" }
janus_integration_tests = { version = "0.5", path = "integration_tests" }
janus_interop_binaries = { version = "0.5", path = "interop_binaries" }
janus_messages = { version = "0.5", path = "messages" }
k8s-openapi = { version = "0.18.0", features = ["v1_24"] }  # keep this version in sync with what is referenced by the indirect dependency via `kube`
kube = { version = "0.82.2", default-features = false, features = ["client", "rustls-tls"] }
opentelemetry = { version = "0.19", features = ["metrics"] }
# prio = { version = "0.12.1", features = ["multithreaded"] }
serde = { version = "1.0.163", features = ["derive"] }
# prio = { version = "0.12.1", features = ["multithreaded"] }
prio = {git = "https://github.com/dpsa-project/libprio-rs.git", branch ="feature-fixedvec-dp", features = ["multithreaded"]}
rstest = "0.17.0"
trillium = "0.2.9"
trillium-api = { version = "0.2.0-rc.3", default-features = false }
trillium-caching-headers = "0.2.1"
trillium-head = "0.2.0"
trillium-opentelemetry = "0.1.0"
trillium-router = "0.3.5"
trillium-testing = "0.5.0"
trillium-tokio = "0.3.1"

[profile.dev]
# Disabling debug info improves build speeds & reduces build artifact sizes, which helps CI caching.
debug = 0

[profile.small]
# We define a profile intended to minimize the eventual binary size, while still allowing for
# relatively fast compilation. It is intended for use in size-constrained testing scenarios, e.g.
# building a binary artifact that ends up embedded in another binary.
inherits = "dev"
opt-level = "z"   # Optimize for size.
debug = false     # Do not generate debug info.
strip = true      # Strip symbols from binary.
