# syntax=docker/dockerfile:1.2
# FROM ekidd/rust-musl-builder:stable AS builder

from rust AS builder
# ENV HOME=/home/root
# ENV CARGO_HOME=/home/root/cargo
# WORKDIR $HOME/app
WORKDIR /usr/src/myapp
# RUN mkdir -p /home/root/cargo/registry

COPY . .
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,sharing=private,target=/usr/src/myapp/target \
    # sudo chown -R rust: target /home/rust/.cargo && \
    cargo build --release -p janus_aggregator --bin aggregator --bin collection_job_driver --bin aggregation_job_driver --bin aggregation_job_creator --features=prometheus,otlp,fpvec_bounded_l2 && \
    # Copy executable out of the cache so it is available in the final image.
    cp target/release/aggregator ./aggregator && \
    cp target/release/collection_job_driver ./collection_job_driver && \
    cp target/release/aggregation_job_driver ./aggregation_job_driver && \
    cp target/release/aggregation_job_creator ./aggregation_job_creator

FROM alpine
ARG BINARY=aggregator
ENV BINARY=$BINARY
COPY --from=builder /usr/src/myapp/$BINARY .
USER 1000
ENTRYPOINT ["/bin/sh", "-c", "exec /$BINARY \"$0\" \"$@\""]

