[package]
name = "janus_integration_tests"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
kube-openssl = ["kube/openssl-tls"]

[dependencies]
anyhow = "1"
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.21.0"
futures = "0.3.26"
hex = "0.4"
janus_aggregator = { workspace = true, features = ["test-util"] }
janus_client.workspace = true
janus_core = { workspace = true, features = ["test-util"] }
janus_interop_binaries = { workspace = true, features = ["testcontainer"] }
janus_messages.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
portpicker = "0.1"
# prio = { version = "0.10.0", features = ["multithreaded"] }
# prio = {git = "https://github.com/dpsa-project/libprio-rs.git", branch ="release/0.10-hotfix-normvector-bugfix", features = [], default-features = false }
prio = {git = "https://github.com/dpsa-project/libprio-rs.git", branch ="feature-simple-dp", features = ["multithreaded"]}
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0.93"
testcontainers = "0.14.0"
tokio = { version = "1", features = ["full", "tracing"] }
tracing = "0.1.37"
url = { version = "2.3.1", features = ["serde"] }

[dev-dependencies]
http = "0.2"
itertools = "0.10"
janus_collector = { workspace = true, features = ["test-util"] }
tempfile = "3"
