[package]
name = "janus_messages"
description = "Distributed Aggregation Protocol message definitions used in Janus, the server powering ISRG's Divvi Up."
documentation = "https://docs.rs/janus_messages"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
test-util = []

[dependencies]
anyhow.workspace = true
base64 = "0.21.2"
derivative = "2.2.0"
hex = "0.4"
num_enum = "0.7.0"
# We can't pull prio in from the workspace because that would enable default features, and we do not
# want prio/crypto-dependencies
# prio = { version = "0.14.1", features = ["multithreaded"] }
# prio = {git = "https://github.com/divviup/libprio-rs.git", branch ="main", features = ["multithreaded"]}
prio = {git = "https://github.com/dpsa4fl/libprio-rs.git", branch ="dp-update-for-janus", features = ["multithreaded", "experimental"]}
rand = "0.8"
serde.workspace = true
thiserror.workspace = true
url = "2.4.0"

[dev-dependencies]
assert_matches = "1"
serde_test.workspace = true
