[package]
name = "janus_interop_binaries"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
test-util = [
    "dep:hex",
    "dep:futures",
    "dep:lazy_static",
    "dep:regex",
    "dep:zstd",
]
testcontainer = [
    "dep:janus_build_script_utils",
    "dep:testcontainers",
    "test-util",
]

[dependencies]
anyhow = "1"
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.13.0"
clap = "4.0.15"
fixed = "1.19"
fixed-macro = "1.1.1"
futures = { version = "0.3.24", optional = true }
hex = { version = "0.4", optional = true }
lazy_static = { version = "1", optional = true }
janus_aggregator = { path = "../aggregator" }
janus_client = { path = "../client" }
janus_collector = { path = "../collector" }
janus_core = { path = "../core" }
janus_messages = { path = "../messages" }
opentelemetry = { version = "0.18", features = ["metrics"] }
prio = { version = "0.10.0", features = ["multithreaded"] }
rand = "0.8"
regex = { version = "1", optional = true }
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls"] }
ring = "0.16.20"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
testcontainers = { version = "0.14", optional = true }
tokio = { version = "1.21", features = ["full", "tracing"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"] }
url = { version = "2.3.1", features = ["serde"] }
warp = "0.3"
zstd = { version = "0.11", optional = true }

[dev-dependencies]
janus_interop_binaries = { path = ".", features = ["testcontainer"] }
janus_core = { path = "../core", features = ["test-util"] }
reqwest = { version = "0.11.12", default-features = false, features = ["json"] }
testcontainers = "0.14.0"

[build-dependencies]
janus_build_script_utils = { path = "../build_script_utils", optional = true }
