[package]
name = "janus_interop_binaries"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
fpvec_bounded_l2 = ["dep:fixed", "dep:fixed-macro"]
test-util = [
    "dep:hex",
    "dep:futures",
    "dep:lazy_static",
    "dep:regex",
    "dep:zstd",
]
testcontainer = [
    "dep:janus_build_script_utils",
    "test-util",
]

[dependencies]
anyhow = "1"
backoff = { version = "0.4", features = ["tokio"] }
base64 = "0.20.0"
clap = "4.0.27"
futures = { version = "0.3.25", optional = true }
fixed = { version = "1.19", optional = true }
fixed-macro = { version = "1.1.1", optional = true }
hex = { version = "0.4", optional = true }
lazy_static = { version = "1", optional = true }
janus_aggregator.workspace = true
janus_client.workspace = true
janus_collector.workspace = true
janus_core.workspace = true
janus_messages.workspace = true
opentelemetry = { version = "0.18", features = ["metrics"] }
prio = { version = "0.10.0", features = ["multithreaded"] }
rand = "0.8"
regex = { version = "1", optional = true }
reqwest = { version = "0.11.13", default-features = false, features = ["rustls-tls"] }
ring = "0.16.20"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
testcontainers = { version = "0.14" }
tokio = { version = "1.23", features = ["full", "tracing"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"] }
url = { version = "2.3.1", features = ["serde"] }
warp = "0.3"
zstd = { version = "0.12", optional = true }

[dev-dependencies]
janus_interop_binaries = { workspace = true, features = ["testcontainer", "test-util"] }
janus_core = { workspace = true, features = ["test-util"] }
reqwest = { version = "0.11.13", default-features = false, features = ["json"] }

[build-dependencies]
janus_build_script_utils = { workspace = true, optional = true }
