[package]
name = "janus_aggregator"
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["kube-rustls", "fpvec_bounded_l2"]
fpvec_bounded_l2 = ["dep:fixed", "janus_core/fpvec_bounded_l2"]
tokio-console = ["dep:console-subscriber"]
jaeger = ["dep:tracing-opentelemetry", "dep:opentelemetry-jaeger"]
otlp = [
    "dep:tracing-opentelemetry",
    "dep:opentelemetry-otlp",
    "dep:opentelemetry-semantic-conventions",
    "dep:tonic",
]
prometheus = ["dep:opentelemetry-prometheus", "dep:prometheus"]
test-util = [
    "janus_core/test-util",
    "janus_messages/test-util",
    "dep:lazy_static",
    "dep:testcontainers",
]
kube-rustls = ["kube/rustls-tls"]
kube-openssl = ["kube/openssl-tls"]

[dependencies]
async-trait = "0.1"
anyhow = "1"
atty = "0.2"
backoff = { version = "0.4.0", features = ["tokio"] }
base64 = "0.21.0"
bytes = "1.3.0"
chrono = "0.4"
clap = { version = "4.0.27", features = ["derive", "env"] }
console-subscriber = { version = "0.1.8", optional = true }
deadpool = { version = "0.9.5", features = ["rt_tokio_1"] }
deadpool-postgres = "0.10.4"
derivative = "2.2.0"
futures = "0.3.25"
fixed = { version = "1.19", optional = true }
http = "0.2.8"
http-api-problem = "0.56.0"
hyper = "0.14.23"
itertools = "0.10.5"
janus_core.workspace = true
janus_messages.workspace = true
janus_collector.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
lazy_static = { version = "1", optional = true }
opentelemetry = { version = "0.18", features = ["metrics", "rt-tokio"] }
opentelemetry-jaeger = { version = "0.17", optional = true, features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11", optional = true, features = ["metrics"] }  # ensure that the version of tonic below matches what this uses
opentelemetry-prometheus = { version = "0.11", optional = true }
opentelemetry-semantic-conventions = { version = "0.10", optional = true }
postgres-protocol = "0.6.4"
postgres-types = { version = "0.2.4", features = ["derive", "array-impls"] }
# prio = { version = "0.10.0", features = ["multithreaded"] }
prio = {git = "https://github.com/dpsa-project/libprio-rs.git", branch ="fixedpoint-backported-bugfix", features = ["multithreaded", "experimental"]}
prometheus = { version = "0.13.3", optional = true }
rand = { version = "0.8", features = ["min_const_gen"] }
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls", "json"] }
ring = "0.16.20"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.17"
signal-hook = "0.3.14"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
testcontainers = { version = "0.14.0", optional = true }
thiserror = "1.0"
tokio = { version = "1.24", features = ["full", "tracing"] }
tokio-postgres = { version = "0.7.7", features = ["with-chrono-0_4", "with-serde_json-1", "with-uuid-1", "array-impls"] }
tonic = { version = "0.8", optional = true, features = ["tls", "tls-webpki-roots"] }  # keep this version in sync with what opentelemetry-otlp uses
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-opentelemetry = { version = "0.18", optional = true }
tracing-stackdriver = "0.6.2"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt", "json"] }
url = { version = "2.3.1", features = ["serde"] }
uuid = { version = "1.2.2", features = ["v4"] }
warp = { version = "0.3", features = ["tls"] }

[dev-dependencies]
assert_matches = "1"
hex = { version = "0.4.3", features = ["serde"] }
hyper = "0.14.23"
# Enable `kube`'s `openssl-tls` feature (which takes precedence over the
# `rustls-tls` feature when creating a default client) to work around rustls's
# lack of support for connecting to servers by IP addresses, which affects many
# Kubernetes clusters. Enable the `test-util` feature for various utilities
# used in unit tests.
janus_aggregator = { workspace = true, features = ["fpvec_bounded_l2", "kube-openssl", "test-util"] }
mockito = "0.31.1"
serde_test = "1.0.152"
tempfile = "3.3.0"
tokio = { version = "1", features = ["test-util"] }  # ensure this remains compatible with the non-dev dependency
trycmd = "0.14.10"
wait-timeout = "0.2.0"
