[package]
name = "janus_collector"
description = "Collector for Janus, the server powering ISRG's Divvi Up."
documentation = "https://docs.rs/janus_collector"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
fpvec_bounded_l2 = ["dep:fixed", "dep:fixed-macro", "janus_core/fpvec_bounded_l2"]
test-util = []

[dependencies]
base64 = "0.21.0"
backoff = { version = "0.4.0", features = ["tokio"] }
derivative = "2.2.0"
http-api-problem = "0.56.0"
janus_core.workspace = true
janus_messages.workspace = true
fixed = { version = "1.23", optional = true }
fixed-macro = { version = "1.1.1", optional = true }
rand = { version = "0.8", features = ["min_const_gen"] }
# prio = "0.10.0"
# prio = {git = "https://github.com/dpsa-project/libprio-rs.git", branch ="release/0.10-hotfix-normvector-bugfix", features = ["multithreaded"]}
prio = {git = "https://github.com/dpsa-project/libprio-rs.git", branch ="feature-simple-dp", features = ["multithreaded"]}
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls", "json"] }
retry-after = "0.3.1"
thiserror = "1.0"
tokio = { version = "1.25", features = ["full"] }
tracing = "0.1.37"
url = "2.3.1"

[dev-dependencies]
anyhow = "1"
assert_matches = "1"
base64 = "0.21.0"
chrono = "0.4"
clap = { version = "4.1.6", features = ["derive", "env"] }
janus_collector = { path = ".", features = ["fpvec_bounded_l2", "test-util"] }
janus_core = { workspace = true, features = ["fpvec_bounded_l2", "test-util"] }
mockito = "0.32.3"
rand = "0.8"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"] }
