[package]
name = "janus_collector"
description = "Collector for Janus, the server powering ISRG's Divvi Up."
documentation = "https://docs.rs/janus_collector"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
test-util = []

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
derivative = "2.2.0"
fixed = "1.19"
fixed-macro = "1.1.1"
http-api-problem = "0.55.0"
janus_core = { version = "0.2", path = "../core" }
janus_messages = { version = "0.2", path = "../messages" }
prio = "0.10.0"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls", "json"] }
retry-after = "0.3.1"
thiserror = "1.0"
tokio = { version = "1.21", features = ["full"] }
tracing = "0.1.37"
url = "2.3.1"

[dev-dependencies]
anyhow = "1"
assert_matches = "1"
base64 = "0.13.0"
chrono = "0.4"
clap = { version = "4.0.15", features = ["derive", "env"] }
janus_collector = { path = ".", features = ["test-util"] }
janus_core = { path = "../core", features = ["test-util"] }
mockito = "0.31.0"
rand = "0.8"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"] }
